"""empty message

Revision ID: 4d779bfefd51
Revises: 364d136354e3
Create Date: 2014-04-29 23:18:11.530495

"""

# revision identifiers, used by Alembic.
revision = '4d779bfefd51'
down_revision = '364d136354e3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measure', sa.Column('update_on', sa.DateTime()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measure', 'update_on')
    ### end Alembic commands ###
